package com.jplopez.zzz.entities;

import org.springframework.hateoas.RepresentationModel;

import com.jplopez.zzz.entities.converter.StatTypeConverter;
import com.jplopez.zzz.entities.enums.StatTypes;

import jakarta.persistence.Column;

import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Disc Drive Entity.
 * 
 * Disc Drives are equipment pieces that can be equipped to agents to enhance their stats.
 * Each disc drive has a specific position (1-6), stat type (HP, ATK, DEF, etc.), and base value.
 * Multiple disc drives can belong to the same set to activate set bonuses.
 * 
 * Entities are mapped to tables (or equivalent) to transport the data received in REST controllers
 * to the persistence layer (repositories). Similarly, Entities take the results from querying DBs
 * to the REST controllers who parse them to JSON and response to clients.
 * 
 * @since 1.0
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
@Entity
public class DiscDrive extends RepresentationModel<DiscDrive> {

  /**
   * Primary key identifier for the Disc Drive entity.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @EqualsAndHashCode.Exclude
  private String id;

  /**
   * Unique business identifier for the Disc Drive.
   * This is used for external references and should be unique across all disc drives.
   */
  @Column(nullable = false, unique = true)
  private String discDriveId;

  /**
   * Position slot where this disc drive can be equipped (1-6).
   * Nullable field - different positions provide different stat types and values.
   * Position 1-3 typically provide flat stats (HP, ATK, DEF).
   * Position 4-6 typically provide percentage stats or damage bonuses.
   */
  @Column(nullable = true)
  private int position;

  /**
   * Type of stat this disc drive provides.
   * Nullable field - determines what attribute is enhanced (HP, ATK, DEF, CRIT_RATE, etc.).
   */
  @Column(nullable = true)
  @Convert(converter = StatTypeConverter.class)
  private StatTypes type;

  /**
   * Base numerical value of the stat enhancement.
   * Nullable field - the amount of stat boost this disc drive provides.
   */
  @Column(nullable = true)
  private float baseValue;

  /**
   * Reference to the disc drive set this disc belongs to.
   * Nullable field - used for calculating set bonuses when multiple pieces are equipped.
   */
  @Column(nullable = true)
  private String discDriveSetId;

  /**
   * Manual getter for ID to ensure it's available for HATEOAS link generation.
   * Required due to Lombok and RepresentationModel integration issues.
   * 
   * @return the primary key identifier
   */
  public String getId() {
    return id;
  }

  /**
   * Manual setter for ID to ensure proper entity initialization.
   * 
   * @param id the primary key identifier to set
   */
  public void setId(String id) {
    this.id = id;
  }

}
