package com.jplopez.zzz.entities;

import org.springframework.hateoas.RepresentationModel;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Disc Drive Set Entity.
 * 
 * Disc Drive Sets represent collections of related disc drives that provide set bonuses 
 * when equipped together. Each set typically has 2-piece and 4-piece skill effects
 * that enhance agent performance in different ways.
 * 
 * Entities are mapped to tables (or equivalent) to transport the data received in REST controllers
 * to the persistence layer (repositories). Similarly, Entities take the results from querying DBs
 * to the REST controllers who parse them to JSON and response to clients.
 * 
 * @since 1.0
 */
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
@Entity
public class DiscDriveSet extends RepresentationModel<DiscDriveSet> {

  /**
   * Primary key identifier for the Disc Drive Set entity.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @EqualsAndHashCode.Exclude
  private String id;

  /**
   * Unique business identifier for the Disc Drive Set.
   * This is used for external references and should be unique across all disc drive sets.
   */
  @Column(nullable = false, unique = true)
  private String discDriveSetId;

  /**
   * Display name of the Disc Drive Set.
   * Must be unique and cannot be null.
   */
  @Column(nullable = false, unique = true)
  private String name;

  /**
   * General description of the Disc Drive Set.
   * Nullable field - provides context about the set's purpose or theme.
   */
  @Column(nullable = true)
  private String description;

  /**
   * Description of the 2-piece set bonus effect.
   * Nullable field - describes what happens when 2 pieces from this set are equipped.
   */
  @Column(nullable = true)
  private String twoPieceSkillDescription;

  /**
   * Description of the 4-piece set bonus effect.
   * Nullable field - describes what happens when 4 pieces from this set are equipped.
   */
  @Column(nullable = true)
  private String fourPieceSkillDescription;

  /**
   * Manual getter for ID to ensure it's available for HATEOAS link generation.
   * Required due to Lombok and RepresentationModel integration issues.
   * 
   * @return the primary key identifier
   */
  public String getId() {
    return id;
  }

  /**
   * Manual setter for ID to ensure proper entity initialization.
   * 
   * @param id the primary key identifier to set
   */
  public void setId(String id) {
    this.id = id;
  }

}
